import type { Tables, TablesInsert, TablesUpdate } from "./db/database.types";
import { z } from "zod";

// --- Generic Types ---

/**
 * Standard paginated response structure used across the API.
 */
export interface PaginatedResponse<T> {
  data: T[];
  pagination: {
    page: number;
    limit: number;
    total: number;
  };
}

// --- Base Entity Aliases ---
// These provide a single point of truth linked directly to the Supabase schema.

export type SetEntity = Tables<"sets">;
export type CardEntity = Tables<"cards">;
export type GenerationSessionEntity = Tables<"generation_sessions">;

// --- Set DTOs and Commands ---

/**
 * Data representation of a Set sent to the client.
 * Maps database snake_case to API camelCase.
 */
export type SetDto = Pick<SetEntity, "id" | "name"> & {
  createdAt: SetEntity["created_at"];
};

/**
 * Request body for creating a new set.
 */
export type CreateSetCommand = Pick<TablesInsert<"sets">, "name">;

/**
 * Request body for updating an existing set.
 */
export type UpdateSetCommand = Partial<Pick<TablesUpdate<"sets">, "name">>;

// --- Card DTOs and Commands ---

/**
 * Data representation of a Card sent to the client.
 */
export type CardDto = Pick<CardEntity, "id" | "front" | "back" | "source"> & {
  isKnown: CardEntity["is_known"];
  createdAt: CardEntity["created_at"];
  setId: CardEntity["set_id"];
};

/**
 * Request body for manually creating a card.
 * set_id is usually taken from the URL path /api/sets/{setId}/cards.
 */
export type CreateCardCommand = Pick<TablesInsert<"cards">, "front" | "back">;

/**
 * Request body for updating a card's content or "known" status.
 * Uses TablesUpdate to maintain compatibility with Supabase's expected field names.
 */
export type UpdateCardCommand = Pick<TablesUpdate<"cards">, "front" | "back" | "is_known">;

/**
 * Request body for generating cards from text.
 */
export const GenerateCardsDto = z.object({
  text: z.string().min(1, "Text is required"),
});

// --- AI Generation (M2) Types ---

/**
 * A temporary card structure generated by AI before it is persisted in the DB.
 */
export interface CardProposal {
  id: string; // Temporary client-side UUID
  front: string;
  back: string;
}

/**
 * Input for the AI generation process.
 */
export interface GenerateProposalsCommand {
  text: string;
  targetCardCount: number;
}

/**
 * Response from the AI service containing suggested cards.
 */
export interface GenerateProposalsDto {
  proposals: CardProposal[];
  metadata: {
    inputCharCount: number;
    proposedCount: number;
  };
}

/**
 * Metadata for logging the generation session.
 */
export type TriageSessionMetrics = Pick<
  TablesInsert<"generation_sessions">,
  "input_char_count" | "proposed_count" | "accepted_count" | "rejected_count" | "edited_count"
>;

/**
 * Request body to confirm triage and create cards in bulk.
 */
export interface ConfirmTriageSessionCommand {
  setId: SetEntity["id"];
  cards: Pick<CardEntity, "front" | "back">[];
  session: TriageSessionMetrics;
}

/**
 * Response after successful triage confirmation.
 */
export interface ConfirmTriageSessionDto {
  message: string;
  createdCardsCount: number;
  sessionId: GenerationSessionEntity["id"];
}

// --- Auth DTOs and Commands ---

/**
 * Request body for user login.
 */
export const LoginCommand = z.object({
  email: z.string().email("Invalid email address"),
  password: z.string().min(1, "Password is required"),
});
export type LoginCommand = z.infer<typeof LoginCommand>;

/**
 * Request body for user registration.
 */
export const RegisterCommand = z
  .object({
    email: z.string().email("Invalid email address"),
    password: z.string().min(8, "Password must be at least 8 characters"),
    confirmPassword: z.string().min(1, "Confirm password is required"),
  })
  .refine((data) => data.password === data.confirmPassword, {
    message: "Passwords do not match",
    path: ["confirmPassword"],
  });
export type RegisterCommand = z.infer<typeof RegisterCommand>;

/**
 * Response for successful authentication.
 */
export interface AuthSuccessDto {
  user: {
    id: string;
    email: string;
  };
}

/**
 * Standard error response for auth endpoints.
 */
export interface AuthErrorDto {
  error: {
    code: "validation_error" | "invalid_credentials" | "email_in_use" | "rate_limit" | "server_error";
    message: string;
    details?: Record<string, string[]>;
  };
}
